### ISSUE TITLE
IOS error in libraries Undefined is not an object (evaluating '_expo.Haptic.ImpactStyles[impactStyle]') 

### ISSUE THREAD

**Issue by touskar** [thomaswangio/react-native-gradient-buttons#10]
Hi, 
I have a strange error on IOS, on android it works well. It happen when button is pressed:
" Undefined is not an object (evaluating '_expo.Haptic.ImpactStyles[impactStyle]') "

**Comment by thomaswangio** [comment]
Hey @touskar are you importing Expo correctly? 

https://forums.expo.io/t/typeerror-undefined-is-not-an-object-evaluating-expo-expo-facebook/11402

**Comment by thomaswangio** [comment]
Closing for now, please re-open if you're still running into trouble.
