### ISSUE TITLE
specific borderRadius not working

### ISSUE THREAD

**Issue by StefanYohansson** [thomaswangio/react-native-gradient-buttons#11]
radius props only apply to borderRadius completely, I want to apply to `borderTopRightRadius` and `borderTopLeftRadius` isolated.

**Comment by StefanYohansson** [comment]
trying this: https://github.com/react-native-community/react-native-linear-gradient/issues/156#issuecomment-305457983

**Comment by thomaswangio** [comment]
Have you tried passing custom style props to the button?

```
    <GradientButton
      style={{ borderTopRightRadius: [number], borderTopLeftRadius: [number]}}
    />
```

**Comment by thomaswangio** [comment]
Closing for now, re-open if you still have trouble! @StefanYohansson

**Comment by StefanYohansson** [comment]
no, custom style didn't help @thomaswangio

**Comment by thomaswangio** [comment]
mm ok, i'll try and investigate this when I have some time

**Comment by StefanYohansson** [comment]
seems like a linear gradient limitation
https://github.com/react-native-community/react-native-linear-gradient/issues/154

**Comment by thomaswangio** [comment]
This package is using https://github.com/expo/expo/labels/LinearGradient. Adding this as reference for future requests for this type of feature, should go there!
