### ISSUE TITLE
Cannot read property 'Heavy' of undefined

### ISSUE THREAD

**Issue by louischeminant** [thomaswangio/react-native-gradient-buttons#12]
An error is occurred when I use `impact`.

![simulator screen shot - iphone x - 2019-03-03 at 11 42 40](https://user-images.githubusercontent.com/16012869/53694059-76002880-3da9-11e9-8c31-8b3a05f826bc.png)

Using: 
```
  "dependencies": {
    "apollo-boost": "^0.1.27",
    "expo": "^32.0.0",
    "firebase": "^5.8.4",
    "graphql": "^14.1.1",
    "react": "16.5.0",
    "react-apollo": "^2.4.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-gradient-buttons": "^1.2.9",
    "react-native-showdown": "^0.4.0",
    "react-navigation": "^3.2.1",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
    "styled-components": "^4.1.3"
  }
```

Thanks !

**Comment by thomaswangio** [comment]
Ah, @louischeminant Expo changed the syntax to `ImpactFeedbackStyle` in v31.0.0. Will update.

**Comment by thomaswangio** [comment]
Updated! Please use v.1.3.0 https://www.npmjs.com/package/react-native-gradient-buttons

**Comment by eddyoc** [comment]
Hi I am using
```
"expo": "^32.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
"react-native-gradient-buttons": "^1.3.0",
```

and I still see this exact error. 

If I specify an impactStyle, such as impactStyle='Light', I see the same error with the word 'Light'.

**Comment by eddyoc** [comment]
Ok, I see as per @thomaswangio comment above, changing line 73 to 
```
Haptic.impact(Haptic.ImpactFeedbackStyle[impactStyle]);
```

but this change does not appear to be reflected in v1.3.0 from npm thus far.

**Comment by thomaswangio** [comment]
@eddyoc ahh, sorry about that! I hadn't updated the file in `src`. Just bumped to 1.3.1.
