### ISSUE TITLE
Text Style prop is ignored

### ISSUE THREAD

**Issue by lebga** [thomaswangio/react-native-gradient-buttons#15]
The prop `textStyle` is completely ignored in the code.

**Comment by thomaswangio** [comment]
Hey thanks for the heads up @lebga! So what happened was I confused myself with 2 `index.js` entry point files from when I first started the project. I tried bumping a breaking change from Expo a while ago and accidentally merged changes from the old file.

I deleted the old file, and updated everything. Just updated to `1.3.2` - everything should be working normally now.

**Comment by lebga** [comment]
Works like a charm, thanks for your super fast answer!


Gabriel Lebaudy
*toHero*

Tel:  04 11 93 26 35
*95 rue Pierre Flourens - 34090 Montpellier*
www.tohero.fr   gabriel.lebaudy@tohero.fr <galeb@tohero.fr>

*When your project needs a Hero*


Le jeu. 25 avr. 2019 à 19:08, Thomas Wang <notifications@github.com> a
écrit :
