### ISSUE TITLE
Error: Unable to resolve module `expo`

### ISSUE THREAD

**Issue by akhilsanker** [thomaswangio/react-native-gradient-buttons#17]
Hi,

Getting the error 'Error: Unable to resolve module `expo`', in my react-native cli project.
Any solution to this?

My Environment is as follows:
    "react-native": "0.59.5",
    "react-native-gradient-buttons": "^1.2.9",

Thanks

**Comment by thomaswangio** [comment]
hey @akhilsanker can you update to the latest version? `yarn add react-native-gradient-buttons@latest` or `npm install react-native-gradient-buttons@latest --save`

**Comment by akhilsanker** [comment]
Hi @thomaswangio ,

Updated to the latest version and still facing the same issue.

Thanks

**Comment by thomaswangio** [comment]
Oh sorry @akhilsanker, is this a pure RN project not using Expo? This package needs to be refactored to use Expo unimodules to run in RN without Expo. Ref: https://blog.expo.io/you-can-now-use-expo-apis-in-any-react-native-app-7c3a93041331.

**Comment by thomaswangio** [comment]
Related: https://github.com/thomaswangio/react-native-gradient-buttons/issues/13

**Comment by PA55ION** [comment]
@akhilsanker Do you solve this issue? I've got the same issue.

**Comment by duydtd97** [comment]
Hi , you can guide for us that how to use your library  ?  I've got the same problem here.

**Comment by thomaswangio** [comment]
Hey @duydtd97 currently this package only works in Expo projects, not pure React Native. Awaiting a PR for this, will investigate when I have a bit more time. Ref: https://github.com/thomaswangio/react-native-gradient-buttons/issues/13

**Comment by braytonstafford** [comment]
i've created pull request [20](https://github.com/thomaswangio/react-native-gradient-buttons/pull/20)

**Comment by thomaswangio** [comment]
This issue has been resolved thanks to @braytonstafford, I made a few adjustments but everything should be working now without Expo as a dependency. Only need to include `react` and `react-native`! 

see https://github.com/thomaswangio/auth-screens for updated example project using new version `v.2.0.1`

cc: @akhilsanker @PA55ION @duydtd97

**Comment by wahaj-47** [comment]
Hey I still can't use it in my pure react project.

**Comment by thomaswang** [comment]
Hey @wahaj-47 so I'm not too familiar with this, but apparently for pure RN projects Expo is requiring you to install https://github.com/unimodules/react-native-unimodules. 

See tweets from @brentvatne: https://twitter.com/notbrent/status/1240042287674970112

Will update README.
