### ISSUE TITLE
This is not working for me

### ISSUE THREAD

**Issue by dantopa** [thomaswangio/react-native-gradient-buttons#3]
After installing the module, I import and add an element to render and says: JSX element type 'GradientButton' does not have any construct or call signatures

**Comment by thomaswangio** [comment]
I'm assuming you're using typescript. Can you try installing types for React and React Native and see if that solves the issue?

```
    "@types/react": "^16.4.9",
    "@types/react-native": "^0.56.6",
```

Reference: https://github.com/styled-components/styled-components/issues/1079

**Comment by thomaswangio** [comment]
Closing this for now since I think this might be an isolated issue. Please re-open if you're having more trouble.

**Comment by dantopa** [comment]
Hi, yes, sorry, I'm using react native with typescript. But I have that dependencies already installed. Any suggestion?

**Comment by thomaswangio** [comment]
Ah I see! Haha I'm not too familiar with typescript, but from there's another user from that thread that found you might have to enable Typescript and reload if you're in VS Code: https://github.com/styled-components/styled-components/issues/1079#issuecomment-412215471. 

Try this?
