### ISSUE TITLE
There is bug when installing this in a non Pure RN 0.57.0 project without expo

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [thomaswangio/react-native-gradient-buttons#4]
It says duplicate data found in node modules.

**Comment by thomaswangio** [comment]
@ManigandanRaamanathan Hey, I'm so sorry. I for some reason added `react-native` as a dependency in the package. Removed and updated to v1.2.9 (https://www.npmjs.com/package/react-native-gradient-buttons).

Let me know if it works, closing this for now!
