### ISSUE TITLE
Could not install via NPM

### ISSUE THREAD

**Issue by WrathChaos** [thomaswangio/react-native-gradient-buttons#5]
Hello,
I really would like to try this library. Unfortunately, after installation with NPM. It simply throws an error about "Could not find the module". 
I could not fix the error. 

If you have time, please take care of it :) 
Thank you

**Comment by thomaswangio** [comment]
@WrathChaos Hey, I'm so sorry. I for some reason added `react-native` as a dependency in the package. Removed and updated to v1.2.9 (https://www.npmjs.com/package/react-native-gradient-buttons).

**Comment by thomaswangio** [comment]
As for circle gradient button, yes you can! Just set props of width and height to be equal, then a border-radius prop of 50%. That would do the trick!

**Comment by thomaswangio** [comment]
Closing this for now, please re-open if there's still issues.

**Comment by WrathChaos** [comment]
Thank you so much @thomaswangio  :)
